### ISSUE TITLE
DHT11 - Humidity reading timing issue?

### ISSUE THREAD

**Issue by openSoftMan** [CHERTS/esp8266-dht11_22#1]
Every once in a while I get an "off" humidity reading with DHT11.  Is the sensor producing this? ( notice the "54.0" in the last column):

18:15:43 - 132,25.0,42.0
18:16:28 - 133,25.0,40.0
18:17:13 - 134,25.0,41.0
18:17:58 - 135,25.0,54.0
18:18:43 - 136,24.0,44.0
18:19:28 - 137,25.0,44.0
18:20:13 - 138,25.0,43.0
18:20:58 - 139,26.0,43.0
18:21:43 - 140,25.0,42.0
18:22:28 - 141,25.0,42.0
18:23:13 - 142,25.0,45.0
18:23:58 - 143,25.0,41.0
18:24:43 - 144,25.0,42.0
18:25:28 - 145,25.0,43.0
18:26:13 - 146,25.0,40.0
18:26:58 - 147,25.0,43.0
18:27:43 - 148,26.0,43.0
18:28:28 - 149,24.0,44.0
18:29:13 - 150,25.0,43.0
18:29:58 - 151,23.0,44.0
18:30:43 - 152,25.0,41.0
18:31:28 - 153,25.0,54.0
18:32:13 - 154,24.0,44.0
18:32:58 - 155,25.0,40.0
18:33:43 - 156,25.0,43.0
18:34:28 - 157,26.0,43.0

**Comment by cherts** [comment]
see commit 1dc1dd4
