### ISSUE TITLE
multiple sensors using arbitrary GPIOs

### ISSUE THREAD

**Issue by eadf** [CHERTS/esp8266-dht11_22#2]
I've made a fork of your project : https://github.com/eadf/esp8266_dhtxx

I added the functionality to support any number of sensors on any GPIOs (one per GPIO or even multiplexed)
I also re-arranged the source code so that it is now directly reusable as a module in other projects.

The question is if you want to merge these changes with your project? The number of changes are quite extensive, but none of them are cut in stone.
I can make a pull request if you like.

I'm able to build the console example under Linux & Mac, but i don't have a windows machine to test on.
Maybe you can take a look?

**Comment by cherts** [comment]
Thank eadf, I updated the driver without easygpio, , I used to work with GPIO implementation of firmware nodemcu, see commit 1dc1dd4

**Comment by eadf** [comment]
Looks good. Just two things:
- ~~ when sensor->pin is, for example, 0: the gpio16 module is initiating GPIO16, while the dht22 code is actually reading (and talking about) GPIO0. ~~ oops, i now see what you did there :). But you still have a problem with just gpio16 as the dht22 doesn't use the wrapper to access pin values.
- if you move dht22.c and dht22.h to a separate folder under driver the whole project can be imported (w/o and changes) as a reusable component by other projects (for example using git submodule or subtree). As it is now those projects must make sure that they don't already include gpio16.c and uart.c in any of their modules (maybe that's more a side effect/flaw of how the recursive makefiles work).
  Just like i import submodules in the [fork](https://github.com/eadf/esp8266_dhtxx/tree/master/examples/dependencies)

Does the gpio16 files exist as a maintained, but separate, module somewhere? Or are they just part of nodemcu?

best regards
/eadf

**Comment by cherts** [comment]
The module is part of gpio16.c nodemcu, but some of his refined, you can use in your projects.
Copy files gpio16.c (.h) and dht22.c (.h) in separate folders I do not want, because it complicates the project and Makefile, if someone would need, he will shift as the files it needs.
